import { createWriteStream, mkdirSync, writeFileSync } from "fs";
import { join, resolve } from "path";
import { db } from "@workspace/db";
import { reportExportsTable } from "@workspace/db/schema";
import PDFDocument from "pdfkit";
import ExcelJS from "exceljs";
/**
 * ExportService - Handles PDF and Excel export generation
 */
export class ExportService {
    static EXPORT_DIR = resolve(process.cwd(), "exports", "reports");
    /**
     * Ensure export directory exists (static initializer)
     */
    static ensureExportDir() {
        mkdirSync(ExportService.EXPORT_DIR, { recursive: true });
    }
    constructor() {
        // Instance constructor for compatibility, but all methods are static
        ExportService.ensureExportDir();
    }
    /**
     * Export report data to PDF format
     */
    static async exportToPdf(reportData, options, generatedBy) {
        ExportService.ensureExportDir();
        return new Promise((resolve, reject) => {
            try {
                const filename = `${options.reportType}-${Date.now()}.pdf`;
                const filepath = join(ExportService.EXPORT_DIR, filename);
                const doc = new PDFDocument({
                    margin: 50,
                    bufferPages: true,
                });
                const stream = createWriteStream(filepath);
                // Attach event listeners to the stream, not the document
                stream.on("finish", () => resolve(filepath));
                stream.on("error", (err) => reject(err));
                doc.on("error", (err) => reject(err));
                doc.pipe(stream);
                // Header
                doc.fontSize(20).font("Helvetica-Bold").text("SMT Verification System", { align: "center" });
                doc.fontSize(12).font("Helvetica").text(options.title || options.reportType, { align: "center" });
                doc.moveDown(0.5);
                // Metadata
                doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: "right" });
                doc.text(`Generated by: ${generatedBy}`, { align: "right" });
                doc.moveDown();
                // Table headers and data
                if (reportData.length > 0) {
                    const headers = Object.keys(reportData[0]);
                    const columnWidth = (doc.page.width - 100) / headers.length;
                    // Headers
                    doc.fontSize(9).font("Helvetica-Bold");
                    let x = 50;
                    headers.forEach((header) => {
                        doc.text(header, x, doc.y, { width: columnWidth, lineBreak: false });
                        x += columnWidth;
                    });
                    doc.moveDown();
                    // Data rows
                    doc.fontSize(8).font("Helvetica");
                    reportData.slice(0, 100).forEach((row) => {
                        let x = 50;
                        headers.forEach((header) => {
                            const value = String(row[header] ?? "");
                            doc.text(value.substring(0, 50), x, doc.y, { width: columnWidth, lineBreak: false });
                            x += columnWidth;
                        });
                        doc.moveDown();
                        // Check if we need a new page
                        if (doc.y > doc.page.height - 100) {
                            doc.addPage();
                        }
                    });
                    if (reportData.length > 100) {
                        doc.moveDown();
                        doc.fontSize(9).text(`... and ${reportData.length - 100} more records`, { align: "center" });
                    }
                }
                else {
                    doc.text("No data available for this report", { align: "center" });
                }
                // Footer
                doc.fontSize(8).text(`Total records: ${reportData.length}`, { align: "center" });
                doc.end();
            }
            catch (error) {
                reject(new Error(`Failed to export PDF: ${error instanceof Error ? error.message : String(error)}`));
            }
        });
    }
    /**
     * Export report data to Excel format
     */
    static async exportToExcel(reportData, options, generatedBy) {
        try {
            ExportService.ensureExportDir();
            const filename = `${options.reportType}-${Date.now()}.xlsx`;
            const filepath = join(ExportService.EXPORT_DIR, filename);
            const workbook = new ExcelJS.Workbook();
            // Main data sheet
            const worksheet = workbook.addWorksheet("Report Data");
            if (reportData.length > 0) {
                const headers = Object.keys(reportData[0]);
                worksheet.columns = headers.map((header) => ({
                    header,
                    key: header,
                    width: Math.min(20, Math.max(10, header.length + 2)),
                }));
                // Add data rows
                reportData.forEach((row) => {
                    worksheet.addRow(row);
                });
            }
            // Summary sheet
            const summarySheet = workbook.addWorksheet("Summary");
            summarySheet.columns = [
                { header: "Property", key: "property", width: 25 },
                { header: "Value", key: "value", width: 40 },
            ];
            summarySheet.addRows([
                { property: "Report Type", value: options.reportType },
                { property: "Title", value: options.title || options.reportType },
                { property: "Generated By", value: generatedBy },
                { property: "Generated At", value: new Date().toLocaleString() },
                { property: "Total Records", value: reportData.length },
            ]);
            // Write file
            await workbook.xlsx.writeFile(filepath);
            return filepath;
        }
        catch (error) {
            throw new Error(`Failed to export Excel: ${error instanceof Error ? error.message : String(error)}`);
        }
    }
    /**
     * Export report data to CSV format
     */
    static async exportToCsv(reportData, options, generatedBy) {
        try {
            const filename = `${options.reportType}-${Date.now()}.csv`;
            const filepath = join(ExportService.EXPORT_DIR, filename);
            if (reportData.length === 0) {
                writeFileSync(filepath, "");
                return filepath;
            }
            // Get all keys from first object
            const headers = Object.keys(reportData[0]);
            const csvContent = [
                headers.map(h => `\"${h.replace(/\"/g, '\"\"')}\"}`).join(","),
                ...reportData.map((row) => headers
                    .map((header) => {
                    const value = row[header];
                    // Always serialize and quote values to prevent CSV injection and data loss
                    let serialized;
                    if (value == null) {
                        serialized = "";
                    }
                    else if (typeof value === "string") {
                        serialized = value;
                    }
                    else if (typeof value === "object") {
                        // Convert objects/arrays to JSON string representation
                        serialized = JSON.stringify(value);
                    }
                    else {
                        // Numbers, booleans, etc.
                        serialized = String(value);
                    }
                    // Escape double quotes by doubling them, then wrap in quotes
                    return `\"${serialized.replace(/\"/g, '\"\"')}\"`;
                })
                    .join(",")),
            ].join("\n");
            writeFileSync(filepath, csvContent);
            return filepath;
        }
        catch (error) {
            throw new Error(`Failed to export CSV: ${error instanceof Error ? error.message : String(error)}`);
        }
    }
    /**
     * Record export activity in database
     */
    static async recordExport(reportId, userId, format, ipAddress, userAgent) {
        try {
            await db.insert(reportExportsTable).values({
                reportId,
                userId,
                format,
                ipAddress,
                userAgent,
            });
        }
        catch (error) {
            console.error("Failed to record export:", error);
            // Don't throw - export should succeed even if recording fails
        }
    }
    /**
     * Get file path for exported report (with path traversal validation)
     */
    static getExportPath(filename) {
        ExportService.ensureExportDir();
        // Security: validate that filename doesn't attempt path traversal
        const fullPath = resolve(join(ExportService.EXPORT_DIR, filename));
        const normalizedExportDir = resolve(ExportService.EXPORT_DIR);
        if (!fullPath.startsWith(normalizedExportDir)) {
            throw new Error("Invalid file path: path traversal detected");
        }
        return fullPath;
    }
    /**
     * Delete exported report file
     */
    static deleteExportFile(filepath) {
        try {
            // Security: only allow deleting files in the export directory
            const normalizedPath = resolve(filepath);
            const normalizedExportDir = resolve(ExportService.EXPORT_DIR);
            if (!normalizedPath.startsWith(normalizedExportDir)) {
                throw new Error("Invalid file path");
            }
            const fs = require("fs");
            if (fs.existsSync(normalizedPath)) {
                fs.unlinkSync(normalizedPath);
            }
        }
        catch (error) {
            console.error("Failed to delete export file:", error);
        }
    }
}
