import { Router } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import bomRouter from "./bom";
import sessionsRouter from "./sessions";
import analyticsRouter from "./analytics";
import feedersRouter from "./feeders";
import componentsRouter from "./components";
import traceabilityRouter from "./traceability";
import auditRouter from "./audit";
import testRouter from "./test";
import trashRouter from "./trash";
import dashboardRouter from "./dashboard";
import timestampRouter from "./timestamp";
import reportsRouter from "./reports";
const router = Router();
router.use(healthRouter);
router.use(usersRouter);
router.use(bomRouter);
router.use(sessionsRouter);
router.use(analyticsRouter);
router.use(feedersRouter);
router.use(componentsRouter);
router.use(traceabilityRouter);
router.use(auditRouter);
router.use(testRouter);
router.use(trashRouter);
router.use(dashboardRouter);
router.use(timestampRouter);
router.use(reportsRouter);
export default router;
